#management.endpoints.web.exposure.include: *
#management.security.enabled: false
server.port: 12080

spring:
  jpa.hibernate.ddl-auto: validate
  datasource:
    url: jdbc:mysql://localhost:3306/football
    username: springuser
    password: password